from jobs.tip_analysis.main import analyze
from jobs.tip_analysis.tip_percentage import analyze_tip_percentage
from jobs.tip_analysis.tip_by_time import analyze_tip_by_time
from jobs.tip_analysis.tip_pay_type import analyze_pay_type