services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    container_name: 'redis-for-twitter'
    volumes:
      - ./data:/data
    environment:
      - REDISEARCH_ARGS=--save 60 1 --appendonly yes
  web:
    build:
      context: .
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - redis

volumes:
  data: 