name: neo4j-movies
services:
  neo4j:
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./data/:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/your_password
    image: neo4j:latest
  web:
    build: web
    ports:
      - 8080:8080
    volumes:
      - ./web/:/app
